/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package seahub.trabajofinaltorneo.igu.principal;

import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JOptionPane;
import seahub.trabajofinaltorneo.igu.ventanas.CrearTorneo;
import seahub.trabajofinaltorneo.logica.Administrador;
import seahub.trabajofinaltorneo.logica.Torneo;

/**
 *
 * @author ianel
 */
public class AdministradorHome extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorHome
     */
    private Administrador adm = new Administrador();
    public AdministradorHome() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setSize(500, 500);
        this.setTitle("Menu de Administrador");
        setVisible(true);
    }
    public AdministradorHome(Administrador adm){
        initComponents();
        this.adm = adm;
        nombreAdministrador.setText(adm.getNombre());        
        setResizable(false);
        setLocationRelativeTo(null);
        setSize(500, 500);
        this.setTitle("Menu de Administrador");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCrearT = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        torneoActual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreAdministrador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearT.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnCrearT.setText("Crear Toneo");
        btnCrearT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, -1));

        cerrarSesion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        torneoActual.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        torneoActual.setText("ver torneos");
        torneoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torneoActualActionPerformed(evt);
            }
        });
        jPanel1.add(torneoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Bienvenido , administrador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        nombreAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAdministradorActionPerformed(evt);
            }
        });
        jPanel1.add(nombreAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 168, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel2.setText("Que desea realizar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTActionPerformed
        //CREAR SENTENCIA IF QUE SE FIJE SI EL ADM YA TIENE UN TORNEO
        boolean verificarTodosFinalizados =true;
        Collection<Torneo> listaTorneosAdm= adm.getTorneoCollection();
        /*for(Torneo auxTorneo : listaTorneosAdm){
            if(auxTorneo.getVigente()==false){
                
            }else{
                verificarTodosFinalizados = true;
            }
        }*/
        if(verificarTodosFinalizados = true){
            JOptionPane.showMessageDialog(null, "CREANDO TORNEO...");
            CrearTorneosP crearTorneos = new CrearTorneosP(adm);
            crearTorneos.setVisible(true);
            crearTorneos.setLocationRelativeTo(null);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "TORNEO EN CURSO");
            
        }
        
    }//GEN-LAST:event_btnCrearTActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void torneoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torneoActualActionPerformed
        VerTorneosAdm torVer = new VerTorneosAdm(adm);
        torVer.setVisible(true);
        this.setVisible(false);
              // TODO add your handling code here:
    }//GEN-LAST:event_torneoActualActionPerformed

    private void nombreAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAdministradorActionPerformed
        
    }//GEN-LAST:event_nombreAdministradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorHome().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearT;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreAdministrador;
    private javax.swing.JButton torneoActual;
    // End of variables declaration//GEN-END:variables
}
