/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package seahub.trabajofinaltorneo.igu.principal;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import seahub.trabajofinaltorneo.logica.Controladora;
import seahub.trabajofinaltorneo.logica.Encriptar;
import seahub.trabajofinaltorneo.logica.Participante;
import static seahub.trabajofinaltorneo.logica.Encriptar.Codificar;
/**
 *
 * @author tinov
 */
public class CambiarDatos extends javax.swing.JFrame {

    /**
     * Creates new form CambiarDatos
     */
    private Participante par;
    public CambiarDatos() {
        initComponents();
    }
    public CambiarDatos(Participante par ){
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setSize(535, 265);
        this.setTitle("");
        setVisible(true);     
        this.par = par;       
        verDatosActuales();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        contrasenaNuevo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreActual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        usuarioActual = new javax.swing.JTextField();
        cantidadActual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        contrasenaActual = new javax.swing.JTextField();
        usuarioNuevo = new javax.swing.JTextField();
        emailNuevo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        nombreNuevo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emailActual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 41, 41));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Escribir contrasena actual:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        contrasenaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(contrasenaNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 150, -1));

        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Contrasena nuevo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));
        jPanel1.add(nombreActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Usuario actual:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel1.add(usuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, -1));
        jPanel1.add(cantidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, -1));

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Email actual:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        contrasenaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaActualActionPerformed(evt);
            }
        });
        jPanel1.add(contrasenaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, -1));
        jPanel1.add(usuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 150, -1));

        emailNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(emailNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 150, -1));

        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Nombre actual:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Cantidad personas actual:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Usuario nuevo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Email nuevo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));
        jPanel1.add(nombreNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, -1));

        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Nombre nuevo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));
        jPanel1.add(emailActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void verDatosActuales(){
        Encriptar codi = new Encriptar();
        Controladora control = new Controladora();
        Participante pAux = control.traerParticipante(par.getIdParticipante());
        nombreActual.setText(par.getNombre());
        usuarioActual.setText(par.getUsuario());
        emailActual.setText(par.getEmail());         
        cantidadActual.setText(String.valueOf(par.getCantidad()));
    }
    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        Controladora control = new Controladora();
        String pass = contrasenaActual.getText();        
        String passC = Codificar(pass);
        boolean sePuede = true;
        Participante aux = control.traerParticipante(par.getIdParticipante());                
        ArrayList<Participante> partArrayAux = control.traerTodoParticipante();
        for(Participante pAux : partArrayAux){
            if(aux.getIdParticipante().equals(pAux.getIdParticipante()) == false){
                if(pAux.getEmail().equals(emailNuevo.getText())||pAux.getUsuario().equals(usuarioNuevo.getText())){
                    sePuede = false;
                    System.out.println("ENTRA CON USUARIO :"+ pAux.getUsuario() + "idPartVer :"+aux.getIdParticipante()+" idPartMover:"+aux.getIdParticipante());
                    break;
                }
            }   
        }
        System.out.println("pass:"+passC+"|pass:"+par.getContrasena());
        if(passC.equals(par.getContrasena()) && sePuede == true ){
            /*if(!cantidadNueva.getText().isEmpty()){
                aux.setNombre(cantidadNueva.getText());
            }*/
            if(!usuarioNuevo.getText().isEmpty()){
                aux.setUsuario(usuarioNuevo.getText());
            }
            if(!emailNuevo.getText().isEmpty()){
                aux.setEmail(emailNuevo.getText());
            }
            if(!contrasenaNuevo.getText().isEmpty()){
                String passMandar = Codificar(contrasenaNuevo.getText());
                System.out.println("CONTRASENA NUEVA:"+passMandar);
                aux.setContrasena(passMandar);
            }           
            /*if(!cantidadNueva.getText().isEmpty()){
                aux.setCantidad(Integer.parseInt(cantidadNueva.getText()));
            }*/
            if(usuarioNuevo.getText().isEmpty()&&emailNuevo.getText().isEmpty()&&contrasenaNuevo.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS ESTAN VACIOS ,NO SE CAMBIO NADA");
            }else{
                JOptionPane.showMessageDialog(null, "DATOS DE USUARIO CAMBIADOS");
                control.editarParticipante(aux);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "CONTRASENA INCORRECTA O USUARIO O EMAIL YA EXISTENTE");
        }         
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        HomeParticipante homePart = new HomeParticipante(par);
        homePart.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void contrasenaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaActualActionPerformed

    private void contrasenaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaNuevoActionPerformed

    private void emailNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JTextField cantidadActual;
    private javax.swing.JTextField contrasenaActual;
    private javax.swing.JTextField contrasenaNuevo;
    private javax.swing.JTextField emailActual;
    private javax.swing.JTextField emailNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreActual;
    private javax.swing.JTextField nombreNuevo;
    private javax.swing.JTextField usuarioActual;
    private javax.swing.JTextField usuarioNuevo;
    // End of variables declaration//GEN-END:variables
}
