/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package seahub.trabajofinaltorneo.igu.principal;

import seahub.trabajofinaltorneo.logica.Administrador;
import seahub.trabajofinaltorneo.logica.Controladora;
import seahub.trabajofinaltorneo.logica.Etapa;
import seahub.trabajofinaltorneo.logica.Participante;
import seahub.trabajofinaltorneo.logica.Torneo;

/**
 *
 * @author tinov
 */
public class ElegirGanadores extends javax.swing.JFrame {

    /**
     * Creates new form ElegirGanadores
     */
    private Torneo tor;
    private Administrador adm;
    private Participante par1;
    private Participante par2;
    private Etapa eta;
    private VistaTorneoVigente vistaTor;
    private Participante ganador = new Participante();
    public ElegirGanadores() {
        initComponents();
    }
    public ElegirGanadores(Torneo tor ,Administrador adm, Participante par1 ,Participante par2 ,Etapa eta , VistaTorneoVigente vistaTor , int etapaActual){
        initComponents();
        this.tor = tor;
        this.adm = adm;
        this.par1 = par1;
        this.par2 = par2;
        this.eta = eta;
        this.vistaTor = vistaTor;
        String pisos = Integer.toString(tor.getPisos());
        piso.setText(pisos);
        String numeroEtapa = Integer.toString(etapaActual);
        etapa.setText(numeroEtapa);
        nombrePar1.setText(par1.getNombre());
        nombrePar2.setText(par2.getNombre());        
    }
    public ElegirGanadores(Torneo tor ,Administrador adm, Participante par1 ,Participante par2 ,Etapa eta ,  int etapaActual){
        initComponents();
        this.tor = tor;
        this.adm = adm;
        this.par1 = par1;
        this.par2 = par2;
        this.eta = eta;
        String pisos = Integer.toString(tor.getPisos());
        piso.setText(pisos);
        String numeroEtapa = Integer.toString(etapaActual);
        etapa.setText(numeroEtapa);
        nombrePar1.setText(par1.getNombre());
        nombrePar2.setText(par2.getNombre());        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPar1 = new javax.swing.JButton();
        btnPar2 = new javax.swing.JButton();
        nombrePar1 = new javax.swing.JTextField();
        nombrePar2 = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        participanteGanador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        piso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        etapa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 41, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(241, 241, 241));
        jLabel1.setForeground(new java.awt.Color(241, 241, 241));
        jLabel1.setText("VS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        btnPar1.setText("Gano");
        btnPar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btnPar2.setText("Gano");
        btnPar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));
        jPanel1.add(nombrePar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, -1));
        jPanel1.add(nombrePar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 130, 20));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Participante Ganador:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        participanteGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participanteGanadorActionPerformed(evt);
            }
        });
        jPanel1.add(participanteGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, -1));

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Piso:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        piso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pisoActionPerformed(evt);
            }
        });
        jPanel1.add(piso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 30, -1));

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Etapa:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jPanel1.add(etapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void participanteGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participanteGanadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participanteGanadorActionPerformed

    private void pisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pisoActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        Controladora control = new Controladora();
        Etapa etaAux = control.traerEtapa(eta.getIdEtapa());
        etaAux.setIdParticipante(ganador);
        control.editarEtapa1(etaAux);        
        vistaTor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnPar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPar1ActionPerformed
        ganador = par1;
        participanteGanador.setText(ganador.getNombre());
    }//GEN-LAST:event_btnPar1ActionPerformed

    private void btnPar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPar2ActionPerformed
        ganador = par2;
        participanteGanador.setText(ganador.getNombre());
    }//GEN-LAST:event_btnPar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirGanadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirGanadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnPar1;
    private javax.swing.JButton btnPar2;
    private javax.swing.JTextField etapa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombrePar1;
    private javax.swing.JTextField nombrePar2;
    private javax.swing.JTextField participanteGanador;
    private javax.swing.JTextField piso;
    // End of variables declaration//GEN-END:variables
}
